### PR TITLE
Feature/all debates

### PR DESCRIPTION
**Pull request by nedtwigg**
Found a video for every single debate.  Pretty much breaks the timeline.  A couple ideas:

Have a radio button, debates/constitution.  When the button changes, we also change the range of the timeline.

Another independent idea is for the timeline to have a fixed height, with its own internal vertical scroll.  Here's an example that works nicely for me on desktop and mobile.
https://datatables.net/examples/basic_init/scroll_xy.html

### CODE REVIEW

**Comment by nedtwigg** [comment]
I added an example that uses the video feature:

**Comment by WebsByTodd** [comment]
Very cool. I can pick up work on this branch after PR #69 gets merged.

**Comment by WebsByTodd** [comment]
Were there no debates between 1960 and 1976?

**Comment by nedtwigg** [comment]
Nope.

**Pull request merged**
