### PR TITLE
Feature/mobile reading

### PR DESCRIPTION
**Pull request by WebsByTodd**
#64

### CODE REVIEW

**Comment by nedtwigg** [comment]
WOW!  What an improvement!  Here's my feedback, from most to least important:

- About us page has huge margins on mobile, and also multiple fonts.
- About us page has links at the bottom, but there's no visual affordance of that:
img_3332
- "This is a Timeline" has no margin at all, and appears to be unstyled:
img_3333
- The header for video evidence has a glitch.  Go to the timeline, pick a Jimmy Carter debate, and then scroll down slowly.  You'll see the problem.
- Takes and Evidence now have the same font.  I think it's good to make the evidence stand out by being in a more authoratative font (e.g. a nice serif) and then have the user content be a more casual sans-serif (Facebook, Twitter, GitHub all use sans).  I think the "About us" page should have the same font as a take.  We're a "page of the people", not a fancy authority.

**Comment by WebsByTodd** [comment]
### Regarding multiple fonts on the about page
I don't think we're finished writing this page yet. I'm following the guidelines on [standards.usa.gov](https://standards.usa.gov/components/typography/#section-/typography/02-pairing-and-styles) which suggest a lead paragraph that stands out from the rest with a different font. I'm using the exact fonts/weights/sizes/line-heights they are using, we just don't have the full structure which should be:

- H1 element as page heading
- Lead paragraph (currently "We Americans can't agree...")
- H2 element as section heading
- Body paragraphs (currently the rest of the page)

#### Do you want to

 A. Add the heading elements, or
 B. Axe the lead paragraph and use the same serif font throughout?

### Regarding video evidence header glitch
I created a new issue for this, #63. It's not readily apparent what's causing this but the investigation is in the pipeline.

Everything else you mentioned will be addressed.

**Comment by nedtwigg** [comment]
I vote for B. Axe the lead paragraph and use the same serif font throughout.  If the lead paragraph were visually next to the other paragraphs, then maybe A could make sense.  But because the comic separates them, I think it looks like a bug.

**Comment by WebsByTodd** [comment]
Regarding serif vs. sans-serif, Medium uses a serif font. Takes are longer form than tweets and Facebook posts, and serif makes readability easier. The current visual distinction between user text and evidence blocks is that evidence blocks are italicized.

I agree there could be a better distinction than what we currently have, and unless readability doesn't concern you I don't think swapping serif for sans-serif should be the distinction. Maybe weight and/or size?

**Comment by nedtwigg** [comment]
I disagree about Takes being longer than tweets and Facebook posts.  I think Takes are exactly the size of a large-ish Facebook post, and the size of a 5-6 tweet Twitter thread.  Our virality depends on Takes being a natural fit for embedding into Facebook and Twitter.

I'm not a fan of italicizing evidence.  I think an evidence block in a Take should appear like a transparent window straight to the real document, and the real document isn't italicized.

**Comment by WebsByTodd** [comment]
Ok. Then we'll remove the italics and make user text sans.

**Pull request merged**
